import 'package:get/get.dart';
import 'package:upculture/controller/artist/artist_home_controller.dart';

class LocalString extends Translations {
  var controller = Get.put(ArtistHomeController());

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Welcome':"Welcome",
          "App Language": "Language",
          "artistSearch": "Search Name,Profession,District",
          "drawerTitle": 'Department of Culture,UP',
          "price": "Artist Price",
          "profession": "engineer",
          'categories': 'Categories',
          'events': 'Events',
          'cultureHeritage': 'Cultural Heritage',
          'culturalEvent': 'Cultural Events',
          'structureofUP': 'Structure of Uttar Pradesh',
          'office': 'Office',
          'radioJayGhosh': 'Shout out',
          'achievements': 'Achievements',
          'externalLink': 'Our subsidiaries',
          'newChanges': 'New Changes',
          "privacyPolicy": 'Privacy Policy',
          'TandC': 'Terms and Conditions',
          'logout': "Logout",
          // 'events': "Events",
          'startDateofEvent': "Event Started On",
          'goToWebsite': "Go to Website",
          'aboutUs': 'About Us',
          'artistRegistrationTitle': 'Please Verify Your Mobile Number',
          'chooseLanguage': 'Choose Language',
          'artistNameLbl': 'Artist/Team Name',
          'mobileNo': 'Mobile Number',
          'city': 'City',
          'email': 'Email',
          'registerLbl': 'Register',
          'alreadyRegiterLblNameLbl': 'Already Registered? Please Login Here',
          'loginLbl': 'Login',
          'otpVerificationMsg': 'O.T.P Verification',
          'OtpLbl': 'Verify OTP',
          'resendOtp': 'Resend OTP',
          'otpMsg': 'Your OTP has been send to Your registered Mobile Number',
          'registerStep1TopMsg': 'OTP Verified, Please fill the form',
          'artistAption': "Artists e-application for cultural programs",
          'personalDetailsLbl': 'Personal Details',
          'artPhoto': 'Artist Picture',
          'Address': 'Address',
          'dob': 'Date Of Birth',
          'gender': 'Gender',
          'workExperience': 'Experience (Years)',
          'nextPage': 'Next',
          "akashwadi": "Grade/Category of All India Radio/Doordarshan",
          'genre': "Name of Genre",
          'genreArea': 'Genre Area',
          'presentaionLvl':
              "Details/Level of Presentation/Award (National/State/Regional/Local):",
          'district': 'District',
          'membersNo': 'Numbers of Members',
          'presentatoinfee': 'Remuneration of Your Performance',
          'relativesNames':
              'The artist should provide references of any two senior artists or gazetted officers who are well acquainted with them',
          'name': "Name",
          'subname': 'Designation',
          'trainingCerti': "Training Certificate",
          'doordarshan/airCerti': "Doordarshan/AIR - Grade Certificate",
          'auditionLink': "Audition Link",
          'twohundredwords':
              "Other Achievements/Details (which are necessary for the artist's participation, in a maximum of 200 words)",
          'presentFivePhoto':
              "Photos of the Presentation Done (Maximum 5 Photos)",
          'youtubeLink': "YouTube/Other Video Link of the Presentation Done",
          'Artist Name': 'Artist Name',
          'not available': 'Not Available',
          'vidharupName': "Name of the Genre",
          'varisthkalakar': 'Name of Senior Artist or Gazetted Officer',
          'varisthsubname': 'Designation of Senior Artist or Gazetted Officer',
          'save': 'Save',
          'SelectGrade': "Select Grade",
          'Select Genre': 'Select Genre',
          'Select': 'Select',
          // 'presentFivePhoto':
          //     'Photos of the Presentation Done (Maximum 5 Photos)',
          'userLogin': 'User Login',
          'artistLogin': 'Artist Login/Sign UP',
          'generalUser': 'General User',
          'artLogin': 'Artist Login',
          'send': 'Send',
          'or': 'Or',
          'register': 'Register',
          'artistDetails': 'Artist Details',
          'home': 'Home',
          'allArtist': "All Artist",
          'confirmLogout': "Are You Sure? You want to Logout!",
          'yes': 'Yes',
          'no': 'No',
          "facebookLink": "Facebook Link",
          "instagramLink": "Instagram Link",
          'guest':"Guest User",
          "guser":'You are not Registered Artist.'
        },
        'hi_IN': {
          'guser':"आप पंजीकृत कलाकार नहीं हैं.",
          "Welcome":"स्वागत",
          "guest":"अतिथि उपयोगकर्ता",
          "facebookLink": "फेसबुक लिंक",
          "instagramLink": "इंस्टाग्राम लिंक",
          "artistSearch": "खोजें,नाम ,पेशा, जिला",
          "drawerTitle": 'संस्कृति विभाग, उत्तर प्रदेश',
          'city': 'शहर',
          "price": "कलाकार पारिश्रमिक",
          'yes': 'हाँ',
          'no': 'नहींं',
          'confirmLogout': "क्या आप लॉगआउट करना चाहते हैं",
          'artistDetails': 'कलाकार विवरण',
          'register': 'पंजीकरण करेंं',
          "App Language": "भाषा",
          "profession": "अभियंता",
          'categories': 'श्रेणियाँ',
          'events': 'आयोजन',
          'cultureHeritage': 'सांस्कृतिक विरासत',
          'culturalEvent': 'संस्कृति कार्यक्रम',
          'structureofUP': 'उत्तर प्रदेश की संरचना',
          'office': 'कार्यालय',
          'radioJayGhosh': 'रेडियो जयघोष',
          'achievements': 'उपलब्धियां',
          'externalLink': 'हमारे अनुषंग',
          'newChanges': 'नये परिवर्तन',
          "privacyPolicy": 'गोपनीयता नीति',
          'TandC': 'नियम और शर्तें',
          'logout': "लॉग आउट",
          // 'events': 'आयोजन',
          'startDateofEvent': 'आयोजन की आरंभ तिथि',
          'goToWebsite': 'वेबसाइट पर जाये',
          "aboutUs": 'हमारे बारे में',
          'artistRegistrationTitle': 'अपना मोबाइल नंबर सत्यापित करे',
          'chooseLanguage': 'कृपया भाषा का चयन करें',
          'artistNameLbl': 'कलाकार/दल का नाम',
          'mobileNo': 'मोबाइल नंबर',
          'email': 'ईमेल',
          'registerLbl': 'रजिस्टर',
          'alreadyRegiterLblNameLbl': 'पहले से पंजीकृत? कृपया यहाँ लॉगिन करें',
          'loginLbl': 'लॉगिन',
          'otpVerificationMsg': 'ओ0टी0पी0 सत्यापन',
          'OtpLbl': 'ओ0टी0पी0 दर्ज करें',
          'resendOtp': 'ओटीपी पुनः भेजें',
          'otpMsg': 'आपका ओटीपी आपके रजिस्टर मोबाइल नंबर पर भेज दिया गया है',
          'registerStep1TopMsg': "ओटीपी सत्यापित, कृपया फॉर्म भरें",
          'artistAption': "सांस्कृतिक कार्यक्रमों के लिए कलाकार ई-आवेदन",
          'personalDetailsLbl': 'व्यक्तिगत  विवरण',
          'artPhoto': 'कलाकार अपनी फ़ोटो जोड़ें',
          'Address': 'पता',
          'dob': 'जन्म तिथि',
          'gender': 'लिंग',
          'workExperience': 'कार्य अनुभव (वर्ष)',
          'nextPage': 'आगे जाएँ',
          "akashwadi": "आकाशवाणी/ दूरदर्शन का ग्रेड/श्रेणी",
          'genre': "विधा का नाम",
          'genreArea': 'विधा का क्षेत्र ',
          'home': 'मुखपृष्ठ',
          'presentaionLvl':
              "प्रस्तुति / पुरस्कार(अ./ रा./ प्रा./ स्था. ) का विवरण/ स्तर:",
          'district': 'जनपद',
          'membersNo': 'दल में सदस्यों की संख्या',
          'presentatoinfee': "आपकी प्रस्तुति हेतु प्रस्तावित पारिश्रमिक",
          'relativesNames':
              'कलाकार किन्ही दो वरिष्ट कलाकार अथवा राजपत्रित अधिकारी का सन्दर्भ दे जो उन्हें भली भांति जानते हो |\n(I)',
          'name': "नाम",
          'subname': 'पदनाम',
          'trainingCerti': "ट्रेनिंग सर्टिफिकेट",
          'doordarshan/airCerti': "दूरदर्शन/एयर/ - ग्रेड सर्टिफिकेट",
          'auditionLink': "ऑडिशन लिंक",
          'twohundredwords':
              "अन्य उपलब्धियां /विवरण (जो कलाकार की प्रतिभागिता हेतु आवश्यक हो अधिकतम 200 शब्दों में)",
          'presentFivePhoto': "किये गए प्रस्तुति का फ़ोटो (अधिकतम 5 फोटो)",
          'youtubeLink': 'किये गए प्रस्तुति का यूट्यूब/ अन्य वीडियो लिंक',
          'Artist Name': 'आर्टिस्ट नाम',
          'not available': 'उपलब्ध नहीं है',
          'vidharupName': "विधा रूप का नाम",
          'varisthkalakar': 'वरिष्ठ कलाकार या राजपत्रित अधिकारी का नाम:',
          'varisthsubname': 'वरिष्ठ कलाकार या राजपत्रित अधिकारी का पदनाम:',
          'save': 'सुरक्षित करें',
          'SelectGrade': "ग्रेड चुनें",
          'Select Genre': 'विधा चुनें',
          'Select': 'चुनें',
          'userLogin': 'उपयोगकर्ता लॉगिन्',
          'generalUser': 'सामान्य उपयोगकर्ता',
          'artistLogin': 'कलाकार लॉगिन/साइनअप',
          'artLogin': 'कलाकार लॉगिन',
          'send': 'भेजें',
          'or': 'या',
          'allArtist': "सभी श्रेणी"
        },
      };
}
